name: Scheduled AWS Nuke

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run AWS Nuke
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws-nuke -c nuke-config.yml  # Adjust the command based on how AWS Nuke is executed in your environment
