name: AWS Nuke on Main Push

on:
  push:
    branches:
      - main

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS Nuke
        run: |
          wget -c https://github.com/rebuy-de/aws-nuke/releases/download/v2.25.0/aws-nuke-v2.25.0-linux-amd64.tar.gz -O aws-nuke
          tar -xzvf aws-nuke
          chmod +x aws-nuke
          sudo mv aws-nuke /usr/local/bin/

      - name: Install expect
        run: sudo apt-get -y install expect     

      - name: Run AWS Nuke
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          expect << 'EOD'
            spawn /usr/local/bin/aws-nuke -c nuke-config.yml --no-dry-run
            expect "Do you want to continue?" { send -- "\r" }
            expect eof
          EOD
